### ISSUE TITLE
[8.0] web_debranding: object unbound while evaluating request.env['ir.config_parameter'].get_param('web_debranding.favicon_url', '').strip()

### ISSUE THREAD

**Issue by moylop260** [yelizariev/website-addons#24]
- Steps to reproduce it:
  - Download next repos:
```bash
git clone https://github.com/Vauxoo/server-tools.git -b 8.0
git clone https://github.com/Vauxoo/addons-vauxoo.git -b 8.0
git clone https://github.com/vauxoo/crm.git -b 8.0
git clone https://github.com/vauxoo/rma.git -b 8.0
git clone https://github.com/yelizariev/website-addons -b 8.0
```
  - Start the server:
```bash
./odoo-8.0/openerp-server -d openerp_test --addons-path /home/travis/build/Vauxoo/addons-yelizariev,/home/travis/server-tools,/home/travis/addons-vauxoo,/home/travis/crm,/home/travis/rma,/home/travis/odoo-8.0/addons,/home/travis/odoo-8.0/openerp/addons --test-enable --init crm_claim_summary_report,web_debranding,report
```

 - Expected:
  No errors

 - Saw:
```bash
2015-11-03 22:16:25,632 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: ERROR
2015-11-03 22:16:25,633 23075 INFO openerp_test openerp.addons.report.tests.test_reports: ======================================================================
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: ERROR: test_reports (openerp.addons.report.tests.test_reports.TestReports)
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: Traceback (most recent call last):
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/addons/report/tests/test_reports.py", line 52, in test_reports
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     registry('report').get_html(cr, uid, report_model_ids, r.report_name)
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/addons/report/models/report.py", line 176, in get_html
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.render(cr, uid, [], report.report_name, docargs, context=context)
2015-11-03 22:16:25,633 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/addons/report/models/report.py", line 152, in render
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return view_obj.render(cr, uid, template, values, context=context)
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_ui_view.py", line 1026, in render
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 262, in render
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
2015-11-03 22:16:25,634 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 423, in render_tag_foreach
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 368, in render_tag_raw
2015-11-03 22:16:25,635 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     inner = self.eval_str(template_attributes["raw"], qwebcontext)
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 214, in eval_str
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     val = self.eval(expr, qwebcontext)
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 206, in eval
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 203, in eval
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return qwebcontext.safe_eval(expr)
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 89, in safe_eval
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/tools/safe_eval.py", line 314, in safe_eval
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return eval(c, globals_dict, locals_dict)
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "", line 1, in <module>
2015-11-03 22:16:25,636 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/addons/report/models/report.py", line 135, in translate_doc
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.translate_doc(cr, uid, doc_id, model, lang_field, template, values, context=context)
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/addons/report/models/report.py", line 115, in translate_doc
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.pool['ir.ui.view'].render(cr, uid, template, qcontext, context=ctx)
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_ui_view.py", line 1026, in render
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,637 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 262, in render
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 423, in render_tag_foreach
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,638 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 446, in render_tag_call
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.render(cr, uid, template, d)
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return old_api(self, *args, **kwargs)
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 262, in render
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
2015-11-03 22:16:25,639 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     g_inner.append(self.render_node(current_node, qwebcontext))
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 465, in render_tag_set
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     qwebcontext[template_attributes["set"]] = self.eval_object(template_attributes["value"], qwebcontext)
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 209, in eval_object
2015-11-03 22:16:25,640 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.eval(expr, qwebcontext)
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 206, in eval
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 203, in eval
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return qwebcontext.safe_eval(expr)
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 89, in safe_eval
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/odoo-8.0/openerp/tools/safe_eval.py", line 314, in safe_eval
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return eval(c, globals_dict, locals_dict)
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "", line 1, in <module>
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return getattr(self._get_current_object(), name)
2015-11-03 22:16:25,641 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     return self.__local()
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `   File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/werkzeug/local.py", line 132, in _lookup
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: `     raise RuntimeError('object unbound')
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: ` openerp.addons.base.ir.ir_qweb.QWebException: ""object unbound" while evaluating
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: ` "request.env['ir.config_parameter'].get_param('web_debranding.favicon_url', '').strip()"" while evaluating
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: ` "translate_doc(doc_id, doc_model, 'partner_id.lang','crm_claim_summary_report.summary_report')"
2015-11-03 22:16:25,642 23075 INFO openerp_test openerp.addons.report.tests.test_reports: Ran 1 test in 0.256s
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.addons.report.tests.test_reports: FAILED
2015-11-03 22:16:25,642 23075 INFO openerp_test openerp.addons.report.tests.test_reports:  (errors=1)
2015-11-03 22:16:25,642 23075 ERROR openerp_test openerp.modules.module: Module report: 0 failures, 1 errors
```
[travis log](https://travis-ci.org/Vauxoo/addons-yelizariev/builds/89108319#L410-L524)

**Comment by yelizariev** [comment]
Seems that the issue happens only in travis environment, isn't?

**Comment by moylop260** [comment]
Yes, because travis environment execute `test-enable`.
But I have replied in other docker that I can share you.
IMHO the test of report has fails with this module because a report don't have a `request` variable. Maybe.

**Comment by yelizariev** [comment]
Thank you
